enum ActionTypes {
  GET_ROOMS_STARTED                   = 'GET_ROOMS_STARTED',
  GET_ROOMS_SUCCEED                   = 'GET_ROOMS_SUCCEED',
  GET_ROOMS_FAILED                    = 'GET_ROOMS_FAILED',
  CREATE_PRIVATE_ROOM_IN_LIST_SUCCEED = 'CREATE_PRIVATE_ROOM_IN_LIST_SUCCEED',
  LEAVE_ROOM_IN_LIST_SUCCEED          = 'LEAVE_ROOM_IN_LIST_SUCCEED'
}

export default ActionTypes