enum ActionTypes {
  LOAD_ROOM_HISTORY_STARTED  = 'LOAD_ROOM_HISTORY_STARTED',
  LOAD_ROOM_HISTORY_SUCCEED  = 'LOAD_ROOM_HISTORY_SUCCEED',
  LOAD_ROOM_HISTORY_FAILED   = 'LOAD_ROOM_HISTORY_FAILED',
  SUBSCRIBE_ROOM_SUCCEED     = 'SUBSCRIBE_ROOM_SUCCEED',
  UNSUBSCRIBE_ROOM_SUCCEED   = 'UNSUBSCRIBE_ROOM_SUCCEED',
  SAVE_ROOM_MESSAGES_SUCCEED = 'SAVE_ROOM_MESSAGES_SUCCEED',
  SAVE_ROOM_MESSAGES_FAILED  = 'SAVE_ROOM_MESSAGES_FAILED',
}

export default ActionTypes