enum ActionTypes {
  LOAD_ROOM_HISTORY_STARTED = 'LOAD_ROOM_HISTORY_STARTED',
  LOAD_ROOM_HISTORY_SUCCEED = 'LOAD_ROOM_HISTORY_SUCCEED',
  LOAD_ROOM_HISTORY_FAILED  = 'LOAD_ROOM_HISTORY_FAILED'
}

export default ActionTypes