enum ActionTypes {
  CREATE_PRIVATE_ROOM_STARTED   = 'CREATE_PRIVATE_ROOM_STARTED',
  CREATE_PRIVATE_ROOM_SUCCEED   = 'CREATE_PRIVATE_ROOM_SUCCEED',
  CREATE_PRIVATE_ROOM_FAILED    = 'CREATE_PRIVATE_ROOM_FAILED'
}

export default ActionTypes