enum ActionTypes {
  REGISTER_USER_STARTED  = 'REGISTER_USER_STARTED',
  REGISTER_USER_SUCCEED  = 'REGISTER_USER_SUCCEED',
  REGISTER_USER_FAILED   = 'REGISTER_USER_FAILED',
}

export default ActionTypes