enum ActionTypes {
  LOGIN_USER_STARTED  = 'LOGIN_USER_STARTED',
  LOGIN_USER_SUCCEED  = 'LOGIN_USER_SUCCEED',
  LOGIN_USER_FAILED   = 'LOGIN_USER_FAILED',
  LOGOUT_USER_STARTED = 'LOGOUT_USER_STARTED',
  LOGOUT_USER_SUCCEED = 'LOGOUT_USER_SUCCEED',
  LOGOUT_USER_FAILED  = 'LOGOUT_USER_FAILED',
}

export default ActionTypes