enum ActionTypes {
  INIT_CONNECTION        = 'INIT_CONNECTION',
  CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED',
  CLOSE_CONNECTION       = 'CLOSE_CONNECTION',
  CONNECTION_ERROR       = 'CONNECTION_ERROR'
}

export default ActionTypes