enum ActionTypes {
  GET_SUBSCRIPTIONS_STARTED                   = 'GET_SUBSCRIPTIONS_STARTED',
  GET_SUBSCRIPTIONS_SUCCEED                   = 'GET_SUBSCRIPTIONS_SUCCEED',
  GET_SUBSCRIPTIONS_FAILED                    = 'GET_SUBSCRIPTIONS_FAILED'
}

export default ActionTypes